Topic4
OctaBruzzesi/startup pull request #5
Opened 2016-10-24 17:57 UTC by OctaBruzzesi

2016-10-24 18:31 UTC, afiorenza requested changes
Well done! just a few changes

2016-10-24 18:31 UTC, afiorenza commented on 04-HTML5-APIs/js/canvas.js
> +        if(antiClockWise === 0){
Why are you doing this?

2016-10-24 18:31 UTC, afiorenza commented on 04-HTML5-APIs/Exercise1.html
> +        <p id = "a">
the space between letters is not needed here

2016-10-24 18:31 UTC, afiorenza commented on 04-HTML5-APIs/js/canvasAnimated.js
> +    let animationFrame = window.mRequestAnimationFrame||window.webkitRequestAnimationFrame||window.msRequestAnimationFrame||
Leave space between ||

2016-10-24 18:31 UTC, afiorenza commented on 04-HTML5-APIs/js/jsExercise1.js
> +    var file = e.dataTransfer.files,
remember to use es6 :D

2016-10-24 18:31 UTC, afiorenza commented on 04-HTML5-APIs/js/jsExercise1.js
> +function allowDrop(ev){
Refactor to match a more descriptive name of `ev` like `event`

2016-10-24 18:31 UTC, afiorenza commented on 04-HTML5-APIs/js/jsExercise1.js
> +    writeToScreen('<span style="color: red;">ERROR:</span> ' + evt.data);
The style should go on a stylesheet. And add a class here.

2016-10-24 18:31 UTC, afiorenza commented on 04-HTML5-APIs/js/jsExercise1.js
> +  {
The `{` should go on the above line. The same with other cases.

2016-10-24 18:31 UTC, afiorenza commented on 04-HTML5-APIs/js/jsExercise1.js
> +    websocket.onopen = function(evt) { onOpen(evt) };
the function here only call another function... Why don't you call the function `onOpen` directly?

2016-10-24 18:31 UTC, afiorenza commented on 04-HTML5-APIs/js/jsExercise1.js
> +    writeToScreen('<span style="color: blue;">RESPONSE: ' + evt.data+'</span>');
The style should go on a stylesheet. And add a class here.

2016-10-24 18:31 UTC, afiorenza commented on 04-HTML5-APIs/js/jsExercise1.js
> +    writeToScreen('<span style="color: blue;">RESPONSE: ' + evt.data+'</span>');
Also you could use an es6 template literal here

2016-10-24 18:31 UTC, afiorenza commented on 04-HTML5-APIs/js/jsExercise1.js
> +    var pre = document.createElement("p");
`pre` is not a descriptive name. Please refactor.

2016-10-24 18:31 UTC, afiorenza commented on 04-HTML5-APIs/js/jsExercise1.js
> +  var wsUri = "ws://echo.websocket.org/";
Remember to use es6, also is more legible if you declare global variables on the top of the file.

2016-10-24 20:29 UTC, OctaBruzzesi commented on 04-HTML5-APIs/js/jsExercise1.js
> +    var file = e.dataTransfer.files,
this.constructor.name = '';
that would be es6?

2016-10-24 20:30 UTC, OctaBruzzesi commented on 04-HTML5-APIs/js/jsExercise1.js
> +    var file = e.dataTransfer.files,
or just put let file = ...?

2016-11-07 12:14 UTC, afiorenza approved these changes

2016-11-10 20:54 UTC, afiorenza commented
Remember to fix conflict and merge it

2016-11-21 17:19 UTC, merged